include: 'https://gitlab.com/wisdomwolf/gamefly-calcs/raw/master/.gitlab-ci.yml'

stages:
  - deploy

Git MIRROR:
  stage: deploy
  script:
    - git push --mirror https://$GITHUB_USER:$GITHUB_PASS@github.com/$GITLAB_USER_LOGIN/$CI_PROJECT_NAME.git
