stages:
  - deploy

Git MIRROR:
  stage: deploy
  script:
      - git push --force --prune https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com/$GITLAB_USER_LOGIN/$CI_PROJECT_NAME.git refs/remotes/origin/*:refs/heads/*
